apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: abctechnologies
  name: abctechnologies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abctechnologies
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: abctechnologies
    spec:
      containers:
      - image: drwizzy/abctechnologies:latest
        name: abctechnologies
        ports:
        - containerPort: 8080
        resources: {}
status: {}
