apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xyztechnologies
  name: xyztechnologies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xyztechnologies
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xyztechnologies
    spec:
      containers:
      - image: drwizzy/xyztechnologies
        imagePullPolicy: Always
        name: xyztechnologies
        ports:
        - containerPort: 8080
        resources: {}
status: {}
